# Generated by Django 5.2.3 on 2025-07-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='updated_at',
        ),
    ]
