# Generated by Django 5.2.3 on 2025-07-16 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 17, 19, 18, 25, 16916, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
