# Generated by Django 5.2.3 on 2025-07-16 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_verification_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 17, 20, 5, 9, 767765, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
