# Generated by Django 5.2.3 on 2025-07-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_job_salary_max_job_salary_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
    ]
